TIMEOUT = 30.0

COURSE_ID = 121520
SUBMODULE_ID = 819742

DB_PATH = "test.db"

LOG_FORMAT = "[%(asctime)s] %(name)s:%(levelname)s: %(message)s"
LOG_DATETIME_FORMAT = "%Y.%m.%d %H:%M:%S"
LOG_LEVEL = "INFO"
LOG_FILENAME = "logs.log"

DATETIME_FORMAT = "%A, %d %B %Y, %H:%M"
TASK_SERVICE_INTERVAL_SECONDS = 300
BOT_SERVICE_INTERVAL_SECONDS = 30

BOT_MESSAGE_PARSE_MODE = "HTML"
MIN_REMIND_INTERVAL_SECONDS = 60


LOOP_SLEEP_TIME = 10